// --------------------------------------------------------------
// -                        Aurex Scripts                       -
// --------------------------------------------------------------

npc: npc/aurex/ExpModifier.txt